- CONTRIBUTORS.md
- MAINTAINERS.md
- mkdocs.yml
> Backport template

- prefect_aws/credentials.py
- requirements-dev.txt
This is a simple change that enable type hint for boto3 objects
> Add aws type hint

- .pre-commit-config.yaml
- prefect_aws/__init__.py
- prefect_aws/client_parameters.py
- prefect_aws/s3.py
- requirements-dev.txt
- tests/conftest.py
- tests/test_client_parameters.py
- tests/test_s3.py
This is the implementation of the #25 to allow to use the custom param that boto3 client allow
This PR is for the #25
> 25 add s3 client extra params

- CHANGELOG.md
- CONTRIBUTORS.md
- Adds entry to change log for v0.1.1
> Prep for v0.1.1 release

- CHANGELOG.md
- README.md
- prefect_aws/credentials.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/test_batch.py
- tests/test_credentials.py
- tests/test_s3.py
- tests/test_secrets_manager.py
- Converted AwsCredentials to block
- Added tests for AwsCredentials block
- Corrected import error in README fenced code block
- Bumped prefect version to 2.0b9
- Removed the .result() call and other code affected by the breaking changes of the newer prefect version
- Updated dependency in requirements-dev.txt 
- Included entry point in setup.py
- Added logo placeholder for block
> Convert to block 

- requirements-dev.txt
- requirements.txt
> Fixes requirements so CI doesn't take forever

- README.md
> Fixes missing fence in readme

- requirements-dev.txt
- requirements.txt
Dependabot has been trying upgrade these for a while, but the pipeline fails unless they are both updated at the same time. I've taken matters into by own hands and bumped them both in one PR.
> Bumps botocore and boto3

- docs/stylesheets/extra.css
Pulls in CSS from Prefect 2.0 documentation in https://github.com/PrefectHQ/prefect/pull/6655 to allow use of badges in documentation.
> Add CSS for badges

- README.md
> Update badge colors

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Updates changelog for v0.1.4 release
- Updates PR template to include a section for updating the changelog
> Prep v0.1.4 release

- CHANGELOG.md
- prefect_aws/ecs.py
Fixes a few typos in ECSTask docstring.
- [ x] Summarized PR's changes in the **Unreleased** section of the [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)
> fix typos in docstrings

- .github/workflows/publish-docs.yml
Fixes https://github.com/PrefectHQ/prefect-aws/actions/runs/3206476935/jobs/5240319534
> Add installation of `pyOpenSSL` to resolve error during docs deployment

- requirements-dev.txt
Fixes CI
Closes https://github.com/PrefectHQ/prefect-aws/issues/130
> Pin moto <= 4.0.6

- CHANGELOG.md
Updates change log for new release.
Closes #
> Prep for v0.1.5 release

- CHANGELOG.md
Updates the changelog for a v0.1.6 release to make the `S3Bucket` block usable for remote flow storage in deployments.
Closes #
> Prep for v0.1.6 release

- CHANGELOG.md
- prefect_aws/ecs.py
> Remove the experimental badge from the `ECSTask` block

- CHANGELOG.md
Updates change log in preparation of v0.1.7 release
> Update changelog for 0.1.7 release

- CHANGELOG.md
- requirements.txt
#152 requires `prefect` version 2.6.7 or higher. This PR updates the minimum required version in requirements.txt to reflect that.
> Bumps minimum required `prefect` version

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
Part of https://github.com/PrefectHQ/prefect/pull/7666
- ~[ ] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"~
> Add `ECSTask.kill` for cancellation support

- CHANGELOG.md
> prep-v0.2.0-release

- CHANGELOG.md
> prep-v0.2.1-release

- .cruft.json
- README.md
- prefect_aws/credentials.py
- prefect_aws/ecs.py
- prefect_aws/s3.py
- tests/test_block_standards.py
Adds the block testing standard
> Cruft update

- CHANGELOG.md
- prefect_aws/credentials.py
- requirements.txt
Bump prefect version + inherit from CredentialsBlock
> Inherit from credentials block

- requirements-dev.txt
- requirements.txt
> Adds mypy boto3 req

- prefect_aws/ecs.py
- prefect_aws/s3.py
Adds attribute docstrings for S3Bucket and ECSTask
Closes https://github.com/PrefectHQ/prefect-aws/issues/185
> add attr docstrings

- CHANGELOG.md
> prep-v0.2.4-release

- prefect_aws/projects/steps.py
Closes
related to https://github.com/PrefectHQ/prefect/issues/9188
The linked bug is quite a blocker for me. tasks will sometimes just completely randomly fail upon running with no other changes to configs or definitions or deployments. The failure occurs on pulling the project from s3.
I'm not 100% sure this fixes the linked error and I will need help testing it, but I noticed that it uses `ListObjects` which I believe is deprecated. The previous call to `for obj in bucket_resource.objects.filter(Prefix=folder):` I think could plausibly fail when the number of objects is extremely large (although I don't know why that causes a permission error). In any case if this closes that issue or not, it seems like a good practice to use a paginator.
update: this won't solve the linked issue. I …
> paginated get for large buckets

- .pre-commit-config.yaml
- docs/gen_blocks_catalog.py
- docs/gen_examples_catalog.py
- prefect_aws/client_waiter.py
- prefect_aws/credentials.py
- prefect_aws/ecs.py
- prefect_aws/s3.py
- prefect_aws/secrets_manager.py
- tests/test_credentials.py
- tests/test_ecs.py
- tests/test_s3.py
For consistent formatting of long strings
> Run `black --preview`

- prefect_aws/ecs.py
- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes https://github.com/PrefectHQ/prefect-aws/issues/223
> Slugify tags to ensure compatibility with ECS limitations

- .pre-commit-config.yaml
- docs/gen_blocks_catalog.py
- docs/gen_examples_catalog.py
- prefect_aws/client_parameters.py
- prefect_aws/ecs.py
- prefect_aws/secrets_manager.py
- prefect_aws/workers/ecs_worker.py
- tests/projects/test_steps.py
- tests/test_ecs.py
- versioneer.py
```
pre-commit autoupgrade
pre-commit run --all-files
```
> Upgrade pre-commit tooling

- CHANGELOG.md
- requirements.txt
Prep for 0.3.1 release:
- Updates minimum version for `prefect`
- Updates CHANGELOG.md
> Prep for 0.3.1 release

- prefect_aws/workers/ecs_worker.py
Updates the metadata fields on the`ECSWorker` class. These values are read from the class and stored in the `prefect-collection-registry`, which supports the display of worker type information in the Prefect UI and CLI.
Note: the metadata for this class already matches the values in this PR because the registry was manually updated for this worker. This PR ensures the metadata will persist after the next `prefect-aws` release.
> Updates worker metadata to support UI and CLI experiences

- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes https://github.com/PrefectHQ/prefect-aws/issues/261
> Fix bug where ECS worker could not cancel flow runs

- CHANGELOG.md
> Update CHANGELOG.md for v0.3.2 release

- CHANGELOG.md
> Update CHANGELOG.md for v0.3.3 release

- docs/ecs_guide.md
Minor edits to diagram.
Closes
> Update ecs_guide.md diagram

- docs/ecs_guide.md
> Update ecs_guide.md to fix typo and make capitalization consistent

- CHANGELOG.md
> fix date on changelog for v0.3.5

- README.md
> Update README.md to remove dataflow mention

- docs/ecs_guide.md
> Update ecs guide to remove pinned Prefect docs references

- prefect_aws/workers/ecs_worker.py
closes: https://github.com/PrefectHQ/prefect-aws/issues/346
accidentally modifying the task run request in place
> dont modify task run request

- CHANGELOG.md
I'd like to release the bugfix from #373 as soon as possible
> prep v0.4.9

- prefect_aws/workers/ecs_worker.py
Recent refactor called a function that didn't exist.
> Call existing function for getting recent revision from family

- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes #289 
- [ x ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
- [ x ] Includes tests or only affects documentation.
- [ x ] Passes `pre-commit` checks.
> Generates family field

- docs/index.md
Updates the docs index page to fix a broken example, reorder information, and improve the page.
> Update index to reflect current Prefect recs and fix an example
