PrefectHQ/prefect-aws

- .pre-commit-config.yaml
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/test_secrets_manager.py
This is a new fixture that creates a tmp per pytest run.  I had on going dev with another version of Orion and all the pytest are failing because of that. That fixture allow to have a tmp db of orion everytime
I expect we could extract this fixture to a package pytest-prefect and can be shared with another prefect project in the future
This is an enhancement to the current pytest capability
> Add auto fixture to use tmp db per session

- README.md
Adds missing AwsCredentials import in the first readme example.
> add missing AwsCredentials in readme example

- requirements.txt
Allow a range of `boto3` and `botocore` versions. This will help users not run into version conflicts when using `prefect-aws` and @dependabot will submit fewer dependency update PRs.
> Loosen `boto3` and `botocore` pins

- prefect_aws/ecs.py
- tests/test_ecs.py
Fixes bug where settings are not passed through to the ECS task runs preventing flow runs contacting the API.
> Include base environment variables in `ECSTask` runs

- prefect_aws/ecs.py
Increase timeout on the `ECSTask` block - 30s is too short with Fargate, especially when using SPOT
> Increase timeout on the `ECSTask` block

- requirements-dev.txt
The attributes on the `ECSTask` block aren't showing the docs. Switching to the legacy python handler for `mkdocstrings` picks them up correctly:
> Changes `mkdocstrings` Python handler to support `pydantic` fields

- CHANGELOG.md
- README.md
- docs/batch.md
- docs/client_waiter.md
- docs/credentials.md
- docs/ecs.md
- docs/s3.md
- docs/secrets_manager.md
- mkdocs.yml
Fix misconfigured edit path to enable submitting edits via the "Pencil" edit link.
In addition:
- Adds yaml frontmatter to doc pages
- Frontmatter includes a note indicating that API pages are generated from docstrings in source files. This gives some indication to a user who wants to edit the API docs, but selects the edit pencil and finds a basically blank page.
> Fix ability to edit pages via GitHub edit link

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
Allows additional options or overrides to be passed to the awslogs driver. 
Closes https://github.com/PrefectHQ/prefect-aws/issues/114
> Add `cloudwatch_logs_options` to customize `configure_cloudwatch_logs` behavior

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
This exposes customizations of the payload for ECS task runs, allowing users to set fields not available at the top level or override any of the options that Prefect sets.
We follow the JSON Patch customizations pattern used in the core library for Kubernetes. Tests and examples have been added for the current user requests. Future requests can be followed with new documentation examples, as patches can be challenging to write at times.
Closes https://github.com/PrefectHQ/prefect-aws/issues/115
Closes https://github.com/PrefectHQ/prefect-aws/issues/113
Closes https://github.com/PrefectHQ/prefect-aws/issues/112
> Add support for JSON patch customizations of the `ECSTask` task run payload

- CHANGELOG.md
- prefect_aws/client_parameters.py
- tests/conftest.py
- tests/test_client_parameters.py
- tests/test_s3.py
Added config parameter to AwsClientParameters to support advanced configuration (e.g. accessing public S3 buckets)
Issues #104 and #102
> Added support for advanced AwsClientParameters configuration (e.g. public S3 buckets) and tests

- mkdocs.yml
- prefect_aws/batch.py
- prefect_aws/credentials.py
Reference:
https://mkdocstrings.github.io/python-legacy/usage/#global-only-options
With show_bases, it shows the base class:
With show_category_headings, it groups by methods, attributes, functions, etc, which I like since it's much easier to discern what's what:
However, it makes Attribute names really small (could this be fixed with some CSS @tpdorsey?)
Also, I tried removing the docstring's Attribute/Args section so there's one source of truth, but I like the table more than the way `Field(description=...)` is rendered; also Field doesn't show it's optional.
Here's the before (Type shows up when Args -> Attributes):
If we include both `Field()` and `Attributes` section, the attributes are first shown in the table, then listed again below:
> Tweak mkdocs and docstrings

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3_bucket.py
Closes #140
When using `S3Bucket.put_directory(ignore_file=".prefectignore")` the `filter_files` function is called which returns the `included_files` as strings. But the actual files are of type `path.PosixPath` and includes the whole absolute path.
As an example:
```markdown
**/folder2/*
```
```python
included_files = {'file3.txt', 'folder2', 'file4.txt'}
pathlib.PosixPath("/private/var/folders/h0/jxdxc2_93m74hnycmnckqb3w0000gn/T/pytest-of-niconeumann/pytest-21/test_put_directory_with_ignore1/folder1/file3.txt")
pathlib.PosixPath("/private/var/folders/h0/jxdxc2_93m74hnycmnckqb3w0000gn/T/pytest-of-niconeumann/pytest-21/test_put_directory_with_ignore1/folder1/file4.txt")
pathlib.PosixPath("/private/var/folders/h0/jxdxc2_93m74hnycmnckqb3w0000gn/T/pytest-of-niconeumann/pytest-21/test_put_dir …
```
> Fix ignore_file option in S3Bucket

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3_bucket.py
Fixes a bug where the `basepath` configured on the `S3Bucket` is used twice when calling `put_directory`. The root cause was determined by @neumann-nico in #141. A couple of tests were not reflecting the desired behavior for `S3Bucket.put_directory` and `S3Bucket.read_path`, so those tests have been updated to reflect the expected behavior and the corresponding methods have been updated accordingly.
Closes #141 
> Fixes double basepath error with `S3Bucket.put_directory`

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
Adds a `family` field to the top-level settings, defaults to `prefect` as before but can be overridden.
Generates the task definition family as `"prefect__{flow-name}__{deployment-name}"` if the metadata is passed to  `prepare_for_flow_run` and it is not set already.
See the test cases for exhaustive examples.
Requires https://github.com/PrefectHQ/prefect/pull/7479
Closes #148 
```python
from prefect_aws.ecs import ECSTask
from prefect.orion.schemas.core import Deployment, FlowRun, Flow
print(
ECSTask()
.prepare_for_flow_run(
FlowRun.construct(),
flow=Flow.construct(name="foo"),
deployment=Deployment.construct(name="bar"),
)
.preview()
)
```
```yaml
---
containerDefinitions:
- image: prefecthq/prefect:dev-python3.8
name: prefect
cpu: '1024'
family: prefect__foo__bar
memory: '2048' …
```
> Generate `ECSTask` family names from deployment and flow metadata

- CHANGELOG.md
- prefect_aws/ecs.py
Closes https://github.com/PrefectHQ/prefect-aws/issues/151
This is best viewed [without whitespace changes](https://github.com/PrefectHQ/prefect-aws/pull/153/files?diff=unified&w=1)
> Fix handling when `describe_tasks` does not return any tasks during `ECSTask` watch

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
Replaces https://github.com/PrefectHQ/prefect-aws/pull/168 with updates from review because I didn't want to manually remove all the image added in the test.
Sets `image = Field(default=None)` instead of `image = Field(default_factory=get_prefect_image_name)`
Checks if the input values contain an image or a task definition ARN. If either of those are present, it returns those. If neither are present, it checks the task definition for a Prefect container image and uses that if it is present. If no Prefect container image is found, it uses the default Prefect base image.
Closes https://github.com/PrefectHQ/prefect-aws/issues/138
- Run …
> Respect image from `task_definition_arn` and use default prefect image if no image is provided

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
We were using the incorrect format for the log stream name. This worked by default since the value we were using (family name of "prefect") matched the value we should have been using (container name of "prefect"). When the family name differed, the log stream would be missing.
This fixes the key and adds best-effort testing around this case. Moto does not appear to support log events and I could not get a full test working. However, I did reproduce the previous failure so we at least have test coverage of that.
Closes https://github.com/PrefectHQ/prefect-aws/issues/177
Needs QA against a live service.
- Run `pre-commit install && pre-commit …
> Fix bug where `ECSTask` could fail to stream logs

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Read/write from Windows OS produced object keys with backslashes and no folder hierarchy. This was due to `pathlib` inferring backslashes on Windows when joining `bucket_path`. Backslashes are frowned upon in the [AWS Object key naming](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) guidelines.
Explicitly made `Path` join `bucket_path` POSIX path string.
Closes
> Made S3Bucket._resolve_path Windows-friendly

- .pre-commit-config.yaml
- CHANGELOG.md
- prefect_aws/credentials.py
- prefect_aws/ecs.py
- prefect_aws/s3.py
- tests/test_s3.py
Closes #207
Updated tests to use `credentials` field instead of `aws_credentials` and `minio_credentials` and corrected the resulting errors.
> Fixes bug when `credentials` attribute is used with `write_path` and `read_path`

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
AWS mirror of https://github.com/PrefectHQ/prefect-gcp/pull/151/
> Stop resolve_path defaulting to random UUID if path is ""

- CHANGELOG.md
- docs/projects/steps.md
- mkdocs.yml
- prefect_aws/projects/steps.py
- tests/projects/test_steps.py
Adds `pull_project_from_s3` and `push_project_to_s3` project steps for storing and retrieving projects in S3 buckets.
Closes #226
Closes #227 
Push a project to an S3 bucket:
```yaml
build:
- prefect_aws.projects.steps.push_project_to_s3:
requires: prefect-aws
bucket: my-bucket
folder: my-project
```
Push a project to an S3 bucket using credentials stored in a block:
```yaml
build:
- prefect_aws.projects.steps.push_project_to_s3:
requires: prefect-aws
bucket: my-bucket
folder: my-project
credentials: "{{ prefect.blocks.aws-credentials.dev-credentials }}"
```
Pull a project from S3 using the default credentials and client parameters:
```yaml
build:
- prefect_aws.projects.steps.pull_project_from_s3:
requires: prefect-aws
bucket: my-bucket
folder: my-project
```
Pull a project from S3 using …
> Adds push and pull project steps for S3

- CHANGELOG.md
- prefect_aws/ecs.py
- tests/test_ecs.py
This change adds support for passing strings to the task customizations parameter of the ECSTask block.  
Currently, using the cli to deploy a flow with task customizations as an infra override would result in a validation error upon flow run submission.  Examples below.
deployment command:
```bash
prefect deployment build example_flow.py:flow_1 \
-n base \
-sb s3/common-utils-dev-test/flow-group-1/flow-1 \
-ib ecs-task/common-utils-flow-1-dev-test \
--override 'task_customizations=[{"op": "replace", "path": "/overrides/cpu", "value": "512"}, {"op": "replace", "path": "/overrides/memory", "value": "1024"}]' \
-q prefect-v2-queue-dev-test \
-v dev \
--params '{"param_name": "param_value"}' \
-t common-utils -t flow-group-1 \
-a \
--cron '0 0 * * *'
```
prefect UI shows the following infra …
> feat(ecs.py): Adding support for passing strings to the JsonPatch validator for task customizations. The deployment cli passes them as strings.

- CHANGELOG.md
- prefect_aws/s3.py
- requirements-dev.txt
- tests/test_s3.py
Removes the following deprecated attributes from the `S3Bucket` block:
- basepath
- aws_crednetials
- minio_credentials
Adds a `basepath` property in order to maintain compatibility with storage block based deployments.
> Removes deprecated attributes from `S3Bucket`

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Enables `smart_union` on `S3Bucket` to ensure that the correct model is chosen when using `MinIOCredentials` with the `S3Bucket.credentials` field.
Closes #251 
> Fixes bug where `MinIOCredentials` are not correctly resolved when used  with S3Bucket

- CHANGELOG.md
- docs/index.md
Closes https://github.com/PrefectHQ/prefect-aws/issues/255#issue-1693118658
Changed documentation argument from 
```python
S3Bucket(
bucket_name=bucket_name,
aws_credentials=aws_credentials,
)
```
to
```python
S3Bucket(
bucket_name=bucket_name,
credentials=aws_credentials,
)
```
The original argument does not actually set the AWS credentials in the S3 Bucket Block
> Change argument to create S3Block in "Save an infrastructure and storage blocks" documentation

- CHANGELOG.md
- README.md
- prefect_aws/s3.py
- tests/test_s3.py
Closes https://github.com/PrefectHQ/prefect-aws/issues/253
> Fix s3 prefix path truncations

- prefect_aws/workers/ecs_worker.py
- requirements.txt
- tests/workers/test_ecs_worker.py
Adds support for new base library functionality from https://github.com/PrefectHQ/prefect/pull/9496
> Stream ECS Worker flow run logs to the API

- CHANGELOG.md
- docs/deployments/steps.md
- docs/projects/steps.md
- mkdocs.yml
- prefect_aws/__init__.py
- prefect_aws/deployments/steps.py
- tests/deploments/test_steps.py
This PR removes references to projects in this library except in the ECS Worker guide. Updates to the ECS Worker guide need to wait until steps and CLI commands are updated in the core library.
Renames:
- `prefect.projects` -> `prefect.deployments`
- `pull_project_from_s3` -> `pull_from_s3`
- `push_project_to_s3` -> `push_to_s3`
- `PullProjectFromS3Output` -> `PullFromS3Output`
- `PushProjectToS3Output` -> `PushToS3Output`
Part of https://github.com/PrefectHQ/prefect/issues/9860
> Updates steps to remove projects references

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Can copy an S3 Object from one `S3Bucket` to another `S3Bucket` without reading the entire object into memory. Buckets may have separate credentials and even owners.
Closes
#275
> Stream objects between buckets

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Corrected which bucket resolves the `from_path`. Added a new test bucket fixture to `TestS3Bucket`.
Closes
#290 
> Fix `S3Bucket.stream_from` source path resolution

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
The retrieved task definition looks something like this:
```python
{'compatibilities': ['EC2', 'FARGATE'],
'containerDefinitions': [{'cpu': 0,
'environment': [],
'essential': True,
'image': 'prefecthq/prefect:2-python3.10',
'mountPoints': [],
'name': 'prefect',
'portMappings': [],
'volumesFrom': []}],
'cpu': '1024',
'family': 'prefect__ecs-task-flow__ecs-task-deployment',
'memory': '2048',
'networkMode': 'awsvpc',
'placementConstraints': [],
'registeredAt': datetime.datetime(2023, 2, 23, 16, 52, 39, 140000, tzinfo=tzlocal()),
'registeredBy': 'arn:aws:sts::576866164297:assumed-role/AWSReservedSSO_PowerUserAccess_8115307ed553845e/andrew.h@prefect.io',
'requiresAttributes': [{'name': 'com.amazonaws.ecs.capability.docker-remote-api.1.18'},
{'name': 'ecs.capability.task-eni'}], …
```
> dont break on debug logs

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
> removing-worker-beta

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
- requirements.txt
- tests/workers/test_ecs_worker.py
Adds `tenacity` to retry failed attempts to create a task run for the ECS worker.
Currently, if an ECS task for a flow run cannot be placed in the specified cluster, then the flow run will be marked as crashed. This change will enable the ECS worker to retry the failed task run placement to reduce the likely hood of flow runs crashing due to failed task placement. 
Closes #301
> Adds retries to ECS task run creation for ECS worker

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes #298 
As per the above issue, there are cases where it is necessary to supply specific ECS Worker task configuration. This is an initial attempt to address that. As referenced in the documentation and test updates, a `dict` that supplies the settings available in the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html)
Difficult to provide a code example here because these settings will likely be taken from the Work Pool configuration.
```python
ECSJobConfiguration.from_template_and_values(
base_job_template=ECSWorker.get_default_base_job_template(),
values={
"aws_credentials:" aws_credentials,
"vpc_id:" "vpc-sometest123",
"override_network_configuration:" True,
"network_configuration:" {
"subnets": …
```
> Allow custom awsvpcConfiguration for ECS Worker

- CHANGELOG.md
- prefect_aws/deployments/steps.py
- tests/deploments/test_steps.py
Add as_posix test
Completed tests
Closes #309 
Now handles windows pathing appropriately as posix paths when writing to S3
N/A, only affects existing processing
> Add as_posix to s3 push file paths in deployment step

- prefect_aws/client_parameters.py
- prefect_aws/credentials.py
- prefect_aws/ecs.py
- prefect_aws/s3.py
- prefect_aws/secrets_manager.py
- prefect_aws/workers/ecs_worker.py
- requirements-dev.txt
- tests/test_ecs.py
- tests/workers/test_ecs_worker.py
Following the compatibility work we've done in `prefect`, we also want to apply the
same compatibility changes to all Prefect-maintained collections.  We're following the
convention that Prefect will always use `pydantic<2` idioms, leaning on the
`pydantic.v1` module of `pydantic>2` to aid us in this.  With these changes, we can
operate normally regardless of the installed version.
Until `prefect` fully deprecates `pydantic` versions below 2.0, we'll continue to
maintain that constraint of using only v1 idioms.
This is part of a series of identical PRs for all of our maintained collections.
> Conditional imports to support operating with `pydantic>2` installed

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes #320
Subnet validation in Network Configuration fails when multiple subnets exist in the VPC.
- Resolved an issue where defining subnets in network configuration would erroneously report them as missing in the VPC.
- Adjusted the boto3 describe_subnets call to specifically compare against SubnetId, as it retrieves full subnet details.
> fix: 320 Subnet validation in Network Configuration fails when multiple subnets exist in the VPC

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Added
- `prefect_aws.s3.s3_copy`
- `prefect_aws.s3.s3_move`
- `prefect_aws.s3.S3Bucket.copy_object`
- `prefect_aws.s3.S3Bucket.move_object`
Closes #315
```python
from prefect_aws.s3 import s3_copy, s3_move
@flow
async def test_flow():
await s3_copy(
source_path="object",
source_bucket_name="my-bucket",
target_path="my-bucket/object",
target_bucket_name="my-backup-bucket",
aws_credentials=aws_credentials,
aws_client_parameters=client_parameters,
)
await s3_move(
source_path="object",
source_bucket_name="my-bucket",
target_path="archive/object",
aws_credentials=aws_credentials,
aws_client_parameters=client_parameters,
)
```
```python
from prefect_aws import S3Bucket
my_bucket = S3Bucket("my-bucket")
my_bucket.copy_object("critical/object", "my-bucket/object", …
```
> AWS S3 copy and move tasks and `S3Bucket` methods

- CHANGELOG.md
- prefect_aws/deployments/steps.py
- tests/deploments/test_steps.py
Closes #313 
When using an AwsCredentials block that has a profile name or other additional params, session creation will now work correctly.
N/A
> Fix s3 session creation in deployment steps push_to_s3 and pull_from_s3

- CHANGELOG.md
- prefect_aws/deployments/steps.py
- tests/deploments/test_steps.py
Closes #327
The boto3 client parameter `use_ssl` defaults to `True`. Setting it to `None` here contradicts the default and causes uploads to SSL-only buckets to fail.
Allowing SSL only on S3 is AWS best practice https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html and therefore, this should work without the need to explicitly set use_ssl to true in the client parameters.
> fix ssl default

- docs/ecs_guide.md
Some small corrections to the ECS worker guide.
> ecs guide fixes and clarifications

- CHANGELOG.md
> Update CHANGELOG.md for v0.4.5

- CHANGELOG.md
- prefect_aws/ecs.py
- requirements.txt
- tests/conftest.py
- tests/test_ecs.py
Implements generate_work_pool_base_job_template on the `ECSTask` block to allow users to use an `ECSTask` block to create an ECS work pool.
> Adds ability to publish `ECSTask` block as a `ecs` work pool

- CHANGELOG.md
- prefect_aws/s3.py
- tests/test_s3.py
Closes #210 
Because every field in `AwsCredentials` has a default or default factory, Pydantic considers non-matching credentials dictionaries valid and selects `AwsCredentials` when calling `S3Bucket.parse_obj()`.
```python
from pydantic import BaseModel, Field
from typing import Union
from prefect_aws import AwsCredentials, MinIOCredentials
class S3Bucket(BaseModel):
bucket_name: str = Field(default=...)
credentials: Union[AwsCredentials, MinIOCredentials] = Field(default_factory=AwsCredentials)
if __name__=="__main__":
minio_bucket_parsed = S3Bucket.parse_obj({
"bucket_name": "my_bucket",
"credentials": {
"minio_root_user": "Kevin",
"minio_root_password": "password",
}
})
s3_bucket_parsed = S3Bucket.parse_obj({
"bucket_name": "my_bucket",
"credentials": {
"aws_access_key_id": "1234", …
```
> Fix `S3Bucket.load()` for nested MinIO Credentials block

- CHANGELOG.md
- prefect_aws/client_parameters.py
- prefect_aws/credentials.py
- prefect_aws/s3.py
- tests/test_credentials.py
- tests/test_s3.py
closes #332 
This PR introduces an enhanced default caching strategy for boto client instances within our `AwsCredentials` and `MinIOCredentials` classes.
- We now cache boto client instances by default using Python's `lru_cache` mechanism, keyed on the credentials context (`ctx`) and client type.
- The cache key is derived from a comprehensive hash of the credentials object, including fields like AWS access keys, secret access keys, session tokens, profile names, and region names, along with parameters specific to each client type.
- The `__hash__` method of `AwsCredentials` and `MinIOCredentials` is based on the combination of these fields, ensuring that any changes to the credentials object results in a different hash and thus a new cache entry.
- Thread safety via a global lock …
> provide ability to cache boto client instances directly and on `S3Bucket`

- CHANGELOG.md
- prefect_aws/deployments/steps.py
- tests/deployments/test_steps.py
When using `prefect.yaml`, allows the user to supply a MinIO Credentials block name for the `push_to_s3` and `pull_from_s3` deployment steps.
```yaml
build: null
push:
- prefect_aws.deployments.steps.push_to_s3:
bucket: test
folder: my-project
credentials: "{{ prefect.blocks.minio-credentials.test-creds }}"
pull:
- prefect_aws.deployments.steps.pull_from_s3:
bucket: test
folder: my-project
credentials: "{{ prefect.blocks.minio-credentials.test-creds }}"
deployments:
- name: minio-stored-deployment
entrypoint: flow.py:my_minio_flow
work_pool:
name: my-ecs-pool
is_schedule_active: true
```
Docstring update for `push_to_s3` and `pull_from_s3`:
- …
> Support MinIO Credentials block as credentials for `push_to_s3` and `pull_from_s3`

- prefect_aws/client_parameters.py
- prefect_aws/credentials.py
- prefect_aws/utilities.py
- tests/test_credentials.py
- tests/test_utilities.py
This PR fixes a bug when the `config` object in `AwsClientParameters` is not hashable (which is normally, since its a `dict`)
Closes #372 
> fix client hashing in nested client params case

- CHANGELOG.md
- prefect_aws/workers/ecs_worker.py
- tests/workers/test_ecs_worker.py
Closes https://github.com/PrefectHQ/prefect/issues/7805
Replaces the use of a session object for client creation with a single cached client per client type in the ECS worker. Significantly reduces memory usage when handling multiple flow runs.
Relative memory consumption (depicted by width of allocating call stack) during 50 simultaneous deployment runs, before and after:
Peak memory usage: 902.5 MiB
Peak memory usage: 45.5 MiB
> Use cached boto3 clients in `ECSWorker`

- requirements-dev.txt
were getting a bunch of `AttributeError: 'CallSpec2' object has no attribute 'funcargs'` errors because we were using pytest 8.0
> update pytest requirements

- requirements-dev.txt
- tests/test_lambda_function.py
- tests/test_s3.py
> Removes `pytest-lazy-fixture` dependency to allow `pytest` to be unpinned

- docs/gen_examples_catalog.py
- prefect_aws/workers/ecs_worker.py
i found it hard to read/follow because of how much nesting there was in `_create_task_and_wait_for_start`
random edits are from accidentally running `ruff format .`
> reduce nesting

- prefect_aws/batch.py
Fixes a bug in the documentation for AWS Batch where it references the incorrect order of arguments.
When using the example provided, the "queue " and "job_definiton" were swapped around, resulting in
```
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the SubmitJob operation: JobDefinition name <my_queue_name> does not exist or is not in ACTIVE status.
```
No relevant screenshots
> Fixed Batch docs to reference the correct order of arguments for the batch_submit task

- prefect_aws/ecs.py
- requirements.txt
- tests/test_ecs.py
Adds a deprecation warning to the `ECSTask` block. The ECS worker should be used instead.
Closes
> Deprecate `ECSTask` block

- prefect_aws/s3.py
> fix docstring for `S3Bucket.read_path`

- prefect_aws/s3.py
- tests/test_s3.py
Closes #384
Uses other bucket's `_resolve_path` method when copying to another `S3Bucket` object. If `to_bucket` is a string, doesn't resolve. Copies to `self` when `to_bucket` is None.
```python
from prefect_aws import S3Bucket
source = S3Bucket(bucket_name="source-bucket")
target = S3Bucket(bucket_name="target-bucket", bucket_folder="subpath/")
source.copy_object("abc.txt", "copies/abc.txt", target)
```
> Fix `S3Bucket.copy_object` target path resolution

- .github/workflows/tests.yml
- setup.py
- tests/test_client_waiter.py
Updates test coverage to Python 3.12 and removes references to supporting Python 3.7.
Closes #404 
Closes
> Add Python 3.12 support and remove 3.7 support
